### PR TITLE
Download offboarding script

### PR DESCRIPTION
**Pull request by SenthilKumarSivakami**
Updated steps to download offboarding script.

### CODE REVIEW

**Comment by cricketer94** [comment]
Hi Siva, this looks good. I think one minor thing to add to the instructions is what the user should do if they cannot find the org ID. So if the org ID does not correspond to anything in the table, then they should probably raise a support ticket (or whatever other flow might've been agreed upon earlier)

**Comment by SenthilKumarSivakami** [comment]
> Hi Siva, this looks good. I think one minor thing to add to the instructions is what the user should do if they cannot find the org ID. So if the org ID does not correspond to anything in the table, then they should probably raise a support ticket (or whatever other flow might've been agreed upon earlier)


Thanks @cricketer94 , have updated the content as needed. Pls take a look now.

**Comment by cricketer94** [comment]
Hi @SenthilKumarSivakami this looks good. Approved.

**Review by cricketer94 — APPROVED** [review]
Sorry should have raised it here. Approved!

**Review by shonleii — APPROVED** [review]

**Pull request merged**
